name = "SegmentationModels"
uuid = "45b6eadc-5e60-40a2-8828-8c65d5497b37"
authors = ["Max Freudenberg"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
